resources:
  - name: repository
    type: git
    source:
      username: MarosBenadik
      password: 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
      uri: https://github.com/MarosBenadik/git-repo-pipeline.git
      branch: main
jobs:
  - name: git-commit
    public: true
    plan:
      - get: repository
      - task: commit-file
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              email: mbenadik25@gmail.com
              username: marosbe
              password: ((docker-password))
              repository: marosbe/alpine
              tag: v1
          inputs:
          - name: repository
          outputs:
          - name: repository
          run:
            path: sh
            args:
              - -ec
              - |
                ls -la
                apk update
                apk add git
                cd repository
                ls -la
                touch file.txt
                now=$(date +"%T")
                echo "Current time : $now" > file.txt
                git config --global user.email "mbenadik25@gmail.com"
                git config --global user.name "MarosBenadik"
                git add .
                git commit -m "first push"
      - put: push-to-repo
        resource: repository
        params:
          repository: repository


